name=input("Enter your name: ")
age=int(input("Enter your age: "))
lab=input("Enter your lab name: ")
product_name=input("Enter your product name: ")
product_price=float(input("Enter your product price: "))
product_quantity=int(input("Enter your product quantity: "))
total=product_price*product_quantity
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Lab name: {lab}")
print(f"Product name: {product_name}")
print(f"Product price: {product_price}")
print(f"Product quantity: {product_quantity}")
print(f"total price of {product_name} is {total}")
print(type(name))
print(type(age))
print(type(lab))
print(type(product_name))
print(type(product_price))
print(type(product_quantity))
print(type(total))
print(str(age))
